version: 2

formats:
  - epub
  - pdf

python:
  version: "3.8"
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
        - fuse

sphinx:
  configuration: docs/conf.py

