[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pydatatask"
version = "0.0.1"
authors = [
    { name = "Audrey Dutcher", email = "audrey@rhelmot.io" },
]
description = "Library for constructing data-centric processing pipelines with few invariants"
requires-python = ">=3.8"
keywords = ["pipeline", "processing", "async", "kubernetes", "s3", "mongodb", "docker"]

dependencies = [
    "kubernetes",
    "kubernetes_asyncio",
    "docker-registry-client-async",
    "python-dxf",
    "jinja2",
    "pyyaml",
    "networkx",
    "aiobotocore",
    "motor",
    "ipython",
    "aiofiles",
    "aioshutil",
]

[optional-dependencies]
dev = [
    "kubernetes-typed",
    "types-pyyaml",
    "networkx-stubs",
    "types-aiobotocore[essential]",
]

[urls]
repository = "https://github.com/rhelmot/pydatatask"

[readme]
file = "README.md"
content-type = "text/markdown"

[license]
file = "LICENSE"

[tool.setuptools]
zip-safe = false
package-data = { pydatatask = ["py.typed"] }
