[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pydatatask"
version = "0.0.1"
authors = [
    { name = "Audrey Dutcher", email = "audrey@rhelmot.io" },
]
description = "Library for constructing data-centric processing pipelines"
requires-python = ">=3.10"

dependencies = [
    "kubernetes",
    "dreg-client",
    "python-dxf",
    "jinja2",
    "pyyaml",
    "networkx",
    "minio",
    "pymongo",
    "ipython",
]

[optional-dependencies]
dev = [
    "kubernetes-typed",
    "types-pyyaml",
    "networkx-stubs",
]

[tool.setuptools]
zip-safe = false
package-data = { pydatatask = ["py.typed"] }
