name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Build and Test
    if: always()
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11']
    runs-on: ubuntu-latest
    env:
      PYTHON: ${{ matrix.python }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python }}
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Deps
      run: 'pip install tox'
    - name: Tests
      run: 'tox -e ${{ matrix.python }}'
      env:
        PYDATATASK_TEST_KUBE_CONTEXT: minikube
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        env_vars: PYTHON
        files: ./coverage.xml
        flags: unittests
  analyze:
    name: Static Analysis
    if: always()
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@master
      with:
        python-version: '3.11'
    - name: Deps
      run: 'pip install -e .[dev]'
    - name: Analyze
      run: 'tox -m analyze-ci'
  audit:
    name: Pip Audit
    if: always()
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@master
      with:
        python-version: '3.11'
    - name: install
      run: pip install .
    - uses: pypa/gh-action-pip-audit@v1.0.2
  release:
    name: Release to PyPI
    needs: ["test", "audit", "analyze"]
    if: "github.event_name == 'push' && github.repository == 'rhelmot/pydatatask' && startsWith(github.ref, 'refs/heads/v') && success()"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@master
      with:
        python-version: '3.11'
    - name: Deps
      run: 'pip install build semver'
    - name: Fix Version
      run: './release.py finalize'
    - name: Build
      run: 'python -m build'
    - name: Publish
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
